In [ ]:
def add(a, b):
  return a+ b

In [ ]:
x = 10
y = 20
result = add(x, y)
print(result)

30


In [ ]:
def Welcome():
  print("Welcome to Python Lab")
Welcome()


Welcome to Python Lab


In [ ]:
def square(n):
  return n*n
print(square(10))

100


In [ ]:
def student(name, age = 21):
  print(name, age)
student("Rahul", 25)

Rahul 25


In [ ]:
def square(n):
  return n*n
print(square(10))

100


In [ ]:
def student(name, age):
  print(name, age)
student("Rahul", 25)

Rahul 25


In [ ]:
def student(name, age = 21):
  print(name, age)
student(age = 25, name = "Rahul")

Rahul 25


In [ ]:
def add(a, b):
  return a + b
result1 = add(10, 20)
print(result1)
result2 = add(1,20,30,40,50)
print(result2)

30


TypeError: add() takes 2 positional arguments but 5 were given

In [ ]:
def add(*nums):
  total = 0
  for x in nums:
    total += x
  return (total)
result1 = add(10, 20)
print(result1)
result2 = add(1,20,30,40,50)
print(result2)

30
141


In [ ]:
import numpy as np
n = int(input("How many numbers: "))
numbers = []
for i in range(n):
  x = int(input("Enter a number: "))
  numbers.append(x)

arr = np.array(numbers)
print("Shape", arr.shape)
print("Dim", arr.ndim)
print("type", type(arr))
print("Array Type", arr.dtype)


How many numbers: 5
Enter a number: 1
Enter a number: 2
Enter a number: 3
Enter a number: 4
Enter a number: 5
Shape (5,)
Dim 1
type <class 'numpy.ndarray'>
Array Type int64


In [ ]:
def create_Array(n):
  numbers = []
  for i in range(n):
    x = int(input("Enter a number: "))
    numbers.append(x)
  return np.array(numbers)
n = int(input("How many numbers: "))
arr = create_Array(n)
print("Shape", arr.shape)
print("Dim", arr.ndim)
print("type", type(arr))
print("Array Type", arr.dtype)

How many numbers: 5
Enter a number: 1
Enter a number: 2
Enter a number: 3
Enter a number: 4
Enter a number: 5
Shape (5,)
Dim 1
type <class 'numpy.ndarray'>
Array Type int64


In [ ]:
def cal(a,b):
  return a+b, a-b, a*b, a/b
add, sub, mul, div = cal(10, 20)
print(add,sub, mul, div)

30 -10 200 0.5


In [ ]:
# Inpute number of students
n = int(input("Enter number of students: "))

marks = []

# Input marks of each student
for i in range(n):
  m = float(input(f"Enter marks of students {i+1}: "))
  marks.append(m)

# Calculate minimum, maximum and average
minimum = min(marks)
maximum = max(marks)
Average = sum(marks)/n

# print result
print("Minimum marks: ", minimum)
print("Maximum marks: ", maximum)
print("Average marks: ", Average)

Enter number of students: 5
Enter marks of students 1: 78
Enter marks of students 2: 99
Enter marks of students 3: 58
Enter marks of students 4: 85
Enter marks of students 5: 66
Minimum marks:  58.0
Maximum marks:  99.0
Average marks:  77.2


Reshapping


In [ ]:
data = np.arange(1, 13)
a = data.reshape()

flatter() and ravel()

In [4]:
import numpy as np
data = np.array([[1,2,3],[4,5,6]])
print("Orig data ", data.ndim)
flat1 = data.flatten()
print("Flatten flat1", flat1)
flat2 = data.ravel()
print("Ravel flat2", flat2)

Orig data  2
Flatten flat1 [1 2 3 4 5 6]
Ravel flat2 [1 2 3 4 5 6]


Combining Arrays
# np.concatenate()
# np.vstack()
# np.hstack()


In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))

print("Concatenate: \n", c)
print("vstack:  \n", np.vstack((a,b)))
print("hstack:  \n", np.hstack((a,b)))



Concatenate: 
 [1 2 3 4 5 6]
vstack:  
 [[1 2 3]
 [4 5 6]]
hstack:  
 [1 2 3 4 5 6]


Vectorization

In [ ]:
data = np.array([10,20,30,40,50])
result = []
for x in data:
  result.append(x*2)
print(np.array(result))

[ 20  40  60  80 100]


In [ ]:
vec_result = data*2
print(vec_result)

[ 20  40  60  80 100]


In [ ]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)



[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [ ]:
marks = np.array([35,45,52,68,74,81,90])
passed = marks >= 40
between = marks[(marks >= 50) & (marks <= 80)]
print(f'Masks for marks >= 40 {passed}')
print(f'Passing MArks: {marks[passed]}')
print(f'Marks between 50 and 80 {between}')

Masks for marks >= 40 [False  True  True  True  True  True  True]
Passing MArks: [45 52 68 74 81 90]
Marks between 50 and 80 [52 68 74]


# Broadcasting

In [ ]:
arr = np.array([1,2,3])
res = arr+1
print(res)

[2 3 4]


In [ ]:
a = np.array([2,4,6])
b = np.array([[1,2,3],[7,8,9]])
res = a+b
print(res)

[[ 3  6  9]
 [ 9 12 15]]


In [ ]:
a = np.array([12,24,35,45,60,70])
b = np.array(["Adult","Minnor"])
res = np.where(a>18,"Adult", "Minnor")
print(res)

['Minnor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']
